1) REGISTER FIX//
2) EXCERCISES NOT SHOWING IN DETAILS//
3) EXCERCISES NOT APLYING IN PROGRAMS//
4) UI FOR TRAINER PROGRAMS CREATE ASSIGN TO CLIENT
5) MAIN SCREEN SHOW ONLY ASSIGNED TERMS//
6) CREATE TRAINER ACCOUNT
7) BLOCK ACCOUNT FIX
8) RESET PASSWORD
9) CHANGE LOGIC FOR CREATING TERMS