import React, { createContext, useContext, useEffect, useState } from 'react';

type Theme = 'light' | 'dark';
type Language = 'Serbian' | 'Russian' | 'German' | 'Hungarian' | 'English';

interface SettingsContextType {
    theme: Theme;
    language: Language;
    setTheme: (t: Theme) => void;
    setLanguage: (l: Language) => void;
    t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    English: {
        dashboard: "Dashboard",
        history: "History",
        profile: "Profile",
        settings: "Settings",
        theme: "Theme",
        language: "Language",
        workout_history: "Workout History",
        sessions: "Sessions",
        exercises: "Exercises",
        programs: "Programs",
        clients: "Clients",
        logout: "Logout",
        light: "Light",
        dark: "Dark",
        system_settings: "System Settings",
        save: "Save",
        finish: "Finish",
        trainer_access: "Trainer Access",
        trainer_dashboard: "Trainer Dashboard",
        manage_sessions: "Manage your sessions",
        weekly_schedule: "Weekly Schedule",
        to_rate: "To Rate",
        nothing_to_rate: "Nothing to rate",
        rate_participants: "Rate Participants",
        work_hours: "Work Hours",
        active_participants: "Active participants",
        total_scheduled: "Total scheduled",
        loading: "Loading",
        search_exercises: "Search exercises...",
        filter_category: "Filter Category",
        add_exercise: "Add Exercise",
        training_programs: "Training Programs",
        build_and_manage: "Build and manage routines",
        all_clients: "All clients",
        create_program: "Create Program",
        pick_exercise: "Pick exercise...",
        difficulty: "Difficulty",
        beginner: "Beginner",
        intermediate: "Intermediate",
        advanced: "Advanced",
        title: "Title",
        description: "Description",
        update: "Update",
        assign_to_client: "Assign to Client",
        assigned_to: "Assigned to",
        no_clients_assigned: "No clients assigned yet",
        add_more: "Add more",
        pick_client: "Pick client...",
        confirm_assignment: "Confirm Assignment",
        rest_s: "Rest (s)",
        tempo: "Tempo",
        sets: "Sets",
        reps: "Reps",
        search_programs: "Search programs...",
        client_dashboard: "Client Dashboard",
        client_dashboard_subtitle: "Your weekly overview & progress",
        completed_total: "Completed total",
        avg_rating: "Avg Rating",
        out_of_10: "Out of 10",
        scheduled: "Scheduled",
        ratings_trend: "Ratings Trend",
        recent_sessions: "Recent Sessions",
        no_data_yet: "No data yet",
        no_recent_sessions: "No recent sessions",
        rating: "Rating",
        cancel_session_confirm: "Are you sure you want to cancel this session?",
        session_canceled: "Session canceled",
        search_clients: "Search clients...",
        view_profile: "View Profile",
        progress: "Progress",
        no_results: "No results found",
        public: "Public",
        private: "Private",
        session: "Session",
        loading_sessions: "Loading sessions...",
        no_sessions_found: "No sessions found",
        no_programs_assigned: "No programs assigned",
        email: "Email",
        gender: "Gender",
        age: "Age",
        assigned_programs: "Assigned Programs",
        loading_history: "Loading your history...",
        history_subtitle: "Review your past performance and track your growth.",
        no_sessions_recorded: "No sessions recorded yet",
        no_sessions_recorded_subtitle: "Complete your first session with your trainer to see your logs here!",
        set: "Set",
        session_details: "Session Details",
        program: "Program",
        date: "Date",
        time: "Time",
        type: "Type",
        trainer: "Trainer",
        client: "Client",
        close: "Close",
        delete_session: "Delete Session",
        start_workout: "Start Workout",
        not_assigned_yet: "Not assigned yet",
        no_scheduled_sessions: "No scheduled sessions for this week.",
        group: "Group",
        individual: "Individual",
        cancel: "Cancel",
        failed_to_load_history: "Failed to load history",
        all_time: "All Time",
        this_month: "This Month",
        this_week: "This Week",
        all_programs: "All Programs",
        download_pdf: "Download PDF",
        member_menu: "Member Menu",
        trainer_menu: "Trainer Menu",
        certified_trainer: "Certified Trainer",
        sessions_completed: "Sessions Completed",
        total_programs: "Total Programs",
        total_hours: "Total Hours",
        total_sessions: "Total Sessions",
        total_clients: "Total Clients",
        change_plan: "Change plan",
        plan: "Plan",
        pending: "Pending",
        pending_requests: "Pending requests",
        pending_msg: "Pending change to plan:",
        price: "Price",
        next_renewal: "Next renewal",
        no_plan_found: "No active subscription.",
        client_count: "Clients",
        billing_status: "Billing status",
        trial_end: "Trial ends",
        month: "month",
        activate: "Activate",
        current: "Current",
        downgrade: "Downgrade",
        upgrade: "Upgrade",
        activate_plan_note: "Renews monthly on the activation date.",
        using_clients: "Using {current} of {max} client slots",
        unlimited: "Unlimited",
        your_plan: "Your Plan",
        active_plan: "Active Plan",
        pending_plan_change: "Pending Plan Change",
        no_pending_requests: "No pending requests.",
        approve: "Approve",
        sign_up: "Sign up",
        trainer_signup_note: "Trainers: send first name, last name, email and a social profile link (Instagram/LinkedIn) to verify you are a trainer.",
        client_signup_note: "Only clients register here. Trainer accounts are created via the contact form and admin verification.",
        // Landing Page
        landing_badge: "Training Management Platform",
        fittrack_dashboard: "TRAINMETER DASHBOARD",
        landing_subtitle: "Stay aligned — sessions, programs, and progress in one place.",
        landing_desc: "A clean workflow for scheduling, program delivery, and tracking performance — built for real training businesses.",
        create_client_account: "Create Client Account",
        admin_note: "Official Trainer accounts are managed by Admin",
        sessions_label: "Sessions",
        sessions_val: "Scheduling & capacity",
        clients_label: "Clients",
        clients_val: "Progress & history",
        insights_label: "Insights",
        insights_val: "Trends & feedback",
        feat_scheduling_title: "Scheduling that stays organized",
        feat_scheduling_desc: "Set available sessions, manage capacity, and keep bookings under control — everything stays in one calendar flow.",
        feat_programs_title: "Programs clients actually follow",
        feat_programs_desc: "Create structured programs, assign them in seconds, and keep clients consistent with clear workout guidance.",
        feat_pro_title: "Professional experience",
        feat_pro_desc: "A clean, modern look that makes your service feel premium and trustworthy — from day one.",
        feat_workouts_title: "Clear workouts, better adherence",
        feat_workouts_desc: "Exercise details are easy to follow, so clients know exactly what to do and you spend less time explaining basics.",
        feat_progress_title: "Progress & ratings",
        feat_progress_desc: "See trends over time, collect feedback, and make coaching decisions based on real signals — not guesswork.",

        // About Page
        mission_badge: "The Mission Behind TrainMeter",
        about_title: "ABOUT TRAINMETER",
        about_desc: "TrainMeter is a premium web platform designed for personal trainers, gyms and online coaches. Our mission is to simplify your daily workflow: from scheduling sessions to delivering structured programs — eliminating administrative clutter so you can focus on the grind.",
        for_trainers: "For Trainers",
        for_trainers_p1: "TrainMeter allows you to maintain complete records of your professional work in one place. Easily create and organize training sessions, personalized programs, and specific exercises for each client, complete with video demonstrations.",
        for_trainers_p2: "After every session, you can leave ratings and feedback, giving your clients a crystal-clear view of their progress. Our goal is to lift the administrative burden off your shoulders.",
        for_clients: "For Clients",
        for_clients_p1: "As a client, you get a clear overview of all your programs and exercises prepared by your trainer, including detailed descriptions and video guides. Book your sessions directly through the app based on your trainer's availability.",
        for_clients_p2: "Track exactly when you train, what to expect in each workout, and monitor your performance trends. No more searching through messages and photos — everything is centralized and always accessible.",

        // Legal Pages common
        policy_status: "Policy Status",
        active: "Active",
        last_updated: "Last Updated",
        applies_to: "Applies To",
        all_users: "All users",
        public_website_app: "Public website & app",

        // Terms Of Service
        platform_rules_badge: "Platform Rules",
        terms_of_service_title: "TERMS OF SERVICE",
        terms_subtitle: "These terms define how the platform can be used and what users can expect from the service.",
        terms_sec1_title: "1. Agreement",
        terms_sec1_desc: "By accessing or using TrainMeter, you agree to these Terms of Service and any applicable laws. If you do not agree, do not use the platform.",
        terms_sec2_title: "2. Accounts & Access",
        terms_sec2_li1: "Clients can self-register.",
        terms_sec2_li2: "Trainer accounts are created and managed by an administrator.",
        terms_sec2_li3: "You are responsible for maintaining the confidentiality of your credentials.",
        terms_sec3_title: "3. Acceptable Use",
        terms_sec3_desc: "You agree not to:",
        terms_sec3_li1: "Use the platform for unlawful activities.",
        terms_sec3_li2: "Attempt to access other accounts or restricted data.",
        terms_sec3_li3: "Upload malicious content or disrupt service availability.",
        terms_sec4_title: "4. Training Disclaimer",
        terms_sec4_desc: "TrainMeter is a management platform. Training programs and coaching decisions are the responsibility of trainers and clients. Always follow professional guidance and prioritize safety.",
        terms_sec5_title: "5. Availability",
        terms_sec5_desc: "We aim for reliable service, but availability can be affected by maintenance, updates, or technical issues. We may modify or discontinue features to improve the platform.",
        terms_sec6_title: "6. Limitation of Liability",
        terms_sec6_desc: "To the extent permitted by law, TrainMeter is not liable for indirect damages or losses arising from the use of the platform, including business decisions or training outcomes.",
        terms_sec7_title: "7. Changes to Terms",
        terms_sec7_desc: "We may update these terms. Continued use after updates means you accept the revised terms.",
        terms_sec8_title: "8. Contact",
        terms_sec8_desc: "Questions about these terms can be submitted via the contact page.",

        // Privacy Policy
        privacy_badge: "Privacy & Data",
        privacy_title: "PRIVACY POLICY",
        privacy_subtitle: "This policy explains what information we collect, why we collect it, and how we protect it.",
        privacy_sec1_title: "1. Information We Collect",
        privacy_sec1_p1: "We collect account information such as name, email address, and role (client, trainer, admin). Clients may also have profile details (e.g., age, gender, address) if provided.",
        privacy_sec1_p2: "Trainers may manage training-related data such as sessions, programs, exercises, attendance, progress notes, and feedback/ratings associated with their clients.",
        privacy_sec2_title: "2. How We Use Information",
        privacy_sec2_li1: "To provide the service: scheduling, program delivery, progress tracking, and account access.",
        privacy_sec2_li2: "To maintain security: authentication, access control, and audit logs (admin).",
        privacy_sec2_li3: "To improve reliability and performance of the platform.",
        privacy_sec3_title: "3. Data Sharing",
        privacy_sec3_desc: "We do not sell personal data. Data is shared only:",
        privacy_sec3_li1: "With service providers strictly required to operate the platform (e.g., hosting/email), when applicable.",
        privacy_sec3_li2: "When required by law, regulation, or a valid legal request.",
        privacy_sec4_title: "4. Data Retention",
        privacy_sec4_desc: "We keep data only as long as necessary to provide the service and meet legal/operational obligations. You can request deletion of your account data where applicable.",
        privacy_sec5_title: "5. Security",
        privacy_sec5_desc: "We use appropriate technical and organizational measures to protect data from unauthorized access, loss, or misuse. No system is 100% secure, but we continuously improve safeguards.",
        privacy_sec6_title: "6. Your Rights",
        privacy_sec6_desc: "Depending on your location, you may have rights to access, correct, export, or delete your personal data. Requests can be submitted via the contact page.",
        privacy_sec7_title: "7. Contact",
        privacy_sec7_desc: "For privacy questions or requests, contact us through the platform’s contact page.",

        // Cookie Policy
        cookie_badge: "Cookies & Storage",
        cookie_title: "COOKIE POLICY",
        cookie_subtitle: "This policy explains how cookies and local storage are used to keep the platform secure and functional.",
        cookie_sec1_title: "1. What Cookies Are",
        cookie_sec1_desc: "Cookies are small text files stored in your browser. They help websites remember preferences and maintain sessions.",
        cookie_sec2_title: "2. What We Use",
        cookie_sec2_li1: "Essential: authentication and session continuity.",
        cookie_sec2_li2: "Security: protection against abuse and unauthorized access.",
        cookie_sec2_li3: "Preferences: basic UI preferences where applicable.",
        cookie_sec3_title: "3. Local Storage",
        cookie_sec3_desc: "Some data may be stored locally (e.g., temporary authentication flows) to improve user experience. You can clear this in your browser settings.",
        cookie_sec4_title: "4. Managing Cookies",
        cookie_sec4_desc: "You can control cookies via browser settings. Disabling essential cookies may prevent login or core features from working correctly.",
        cookie_sec5_title: "5. Contact",
        cookie_sec5_desc: "If you have questions about cookies, please contact us via the contact page.",

        // Contact Page
        contact_badge: "Inquiry & Trainer Access",
        get_in_touch: "GET IN TOUCH",
        contact_desc: "Have a question, feedback, or want to request a Trainer Account? Fill out the form below to contact the administrator and we'll get back to you shortly.",
        information: "Information",
        trainer_onboarding: "Trainer Onboarding",
        trainer_onboarding_desc: "Official trainer accounts are manually created by admins to ensure quality.",
        customization: "Customization",
        customization_desc: "Want to adapt TrainMeter to your specific gym or studio needs?",
        full_name: "Full Name",
        email_address: "Email Address",
        your_message: "Your Message",
        msg_placeholder: "Tell us about your request or gym studio...",
        all_fields_required: "All fields are required.",
        error_sending_msg: "An error occurred while sending the message.",
        msg_sent: "Your message has been sent. Thank you!",
        send_message: "Send Message",
        sending: "Sending...",

        // Public Nav
        nav_home: "Home",
        nav_about: "About",
        nav_guide: "Guide",
        nav_contact: "Contact",
        nav_login: "LOG IN",
        nav_register: "REGISTER",
        register_now: "Register Now",

        // App Nav
        nav_dashboard: "Dashboard",
        nav_sessions: "Sessions",
        nav_programs: "Programs",
        nav_clients: "Clients",
        nav_exercises: "Exercises",
        nav_profile: "Profile",
        nav_logout: "Log Out",
        nav_history: "History",

        personal_info: "Personal Information",
        first_name: "First Name",
        last_name: "Last Name",
        male: "Male",
        female: "Female",
        address: "Address",
        edit_profile: "Edit Profile",
        save_changes: "Save Changes",
        saving: "Saving...",
        enter_first_name: "Enter first name",
        enter_last_name: "Enter last name",
        select: "Select...",
        date_of_birth: "Date of Birth",
        reset_change_password: "Reset / Change Password",
        account_blocked_msg: "Account is blocked — functionality is limited",
        profile_load_failed: "Profile could not be loaded.",
        edit: "Edit",
        exercise_library: "Exercise Library",
        manage_movements: "Manage your workout movements",
        new_exercise: "New Exercise",
        exercise_name: "Exercise Name",
        technique_cues: "Technique cues...",
        muscle: "Muscle",
        equipment: "Equipment",
        client_progress: "Client Progress",
        total_workouts: "Total Workouts",
        total_volume: "Total Volume",
        exercises_tracked: "Exercises Tracked",
        max_weight: "Max Weight",
        max_weight_kg: "Max Weight (kg)",
        total_volume_kg: "Total Volume (kg)",
        client_profile: "Client Profile",
        id: "ID",
        showing_last_5: "Showing last 5 sessions",
        live_workout: "Live Workout",
        who_training: "Who are you training?",
        select_participant: "Select participant",
        tap_to_start: "Tap to start logging",
        change: "Change",
        add_set: "Add set",
        finish_workout: "Finish Workout",
        workout_saved: "Workout successfully saved!",
        error_saving_workout: "Error saving workout",
        no_participants_msg: "This session currently has no participants.",
        weight_kg: "Weight (kg)",
        analysis: "Analysis",
        volume: "Volume",
        level: "Level",
        video_url: "Video URL",
        save_exercise: "Save Exercise",
        edit_exercise: "Edit Exercise",
        delete_exercise_confirm: "Are you sure you want to delete this exercise?",
        no_description: "No description",
        no_exercises_found: "No exercises found",
        bench_press: "e.g. Bench Press",
        participant: "participant",
        participants: "participants",
        full_body: "Full Body",
        chest: "Chest",
        back: "Back",
        legs: "Legs",
        shoulders: "Shoulders",
        arms: "Arms",
        core: "Core",
        cardio: "Cardio",
        mobility: "Mobility",
        none: "None",
        bodyweight: "Bodyweight",
        dumbbells: "Dumbbells",
        barbell: "Barbell",
        kettlebell: "Kettlebell",
        machine: "Machine",
        bands: "Bands",
        other: "Other",
        training_schedule: "Training Schedule",
        manage_sessions_bookings: "Manage your sessions and bookings",
        create_new_session: "Create New Session",
        upcoming_sessions: "Upcoming Sessions",
        pick_date_time: "Pick date and time",
        capacity: "Capacity",
        duration_min: "Duration (minutes)",
        individual_tip: "Individual sessions automatically have capacity set to 1.",
        no_sessions_scheduled: "No sessions scheduled",
        awaiting_booking: "Awaiting booking",
        no_program_yet: "No program yet",
        confirm_cancel_term: "Are you sure you want to cancel this term?",
        term_created: "Session slot created! Clients can now book it.",
        term_canceled: "Term canceled",
        browse_book_sessions: "Browse and book available sessions",
        filter_search: "Filter & Search",
        all_types: "All Types",
        all_sessions: "All Sessions",
        free: "Free",
        full: "Full",
        enrolled: "Enrolled",
        book: "Book",
        booking: "Booking",
        canceling: "Canceling",
        not_cancellable: "Not cancellable",
        no_sessions_found_msg: "No sessions found",
        try_adjusting_filters: "Try adjusting your filters",
        search_sessions: "Search sessions...",
        session_booked: "Session booked",
        booking_failed: "Booking failed",
        my_programs: "My Programs",
        programs_of_trainer: "Programs of your trainer",
        no_trainer_assigned: "No trainer assigned",
        select_trainer_msg: "Select a trainer to see their programs.",
        all_levels: "All levels",
        apply: "Apply",
        view_details: "View Details",
        author: "Author",
        loading_programs: "Loading programs",
        no_programs_found_msg: "No programs found for the given filters.",
        no_programs_for_you: "The trainer currently has no programs for you.",
        try_adjusting_search: "Try adjusting search or level.",
        loading_profile: "Loading profile",
        choose_trainer: "Choose Your Trainer",
        pick_trainer_subtitle: "Pick a trainer to unlock sessions and programs",
        no_trainers_available: "No trainers available",
        selecting: "Selecting",
        create_session: "Create Session",
        notes: "Notes",
        position: "Position",
        delete_program: "Delete Program",
        delete_program_confirm: "Are you sure you want to delete this program?",
        program_deleted: "Program deleted",
        program_saved: "Program saved",
        move_up: "Move up",
        move_down: "Move down",
        remove: "Remove",
        create_client: "Create Client",
        password: "Password",
        birth_date: "Birth Date",
        enter_name: "Enter name",
        enter_surname: "Enter surname",
        creating_account: "Creating account...",
        success_create_client: "Client account created successfully",
        failed_create_client: "Failed to create account",
        error_create_client: "Error creating account",
        fill_details_below: "Fill in the details below",
        billing_and_plans: "BILLING & PLANS",
        subscription_overview: "Subscription Overview",
        available_plans: "Available Plans",
        account_not_active: "Account is not active",
        select_plan_to_continue: "Select a plan to continue using TrainMeter.",
        overview: "Overview",
        client_requests_title: "CLIENT REQUESTS",
        no_new_requests: "No new requests",
        client_request_empty_desc: "When a client sends a request, you will see it here.",
        trial: "Trial",
        past_due: "Past Due",
        suspended: "Suspended",
        inactive: "Inactive",
        current_plan: "Current Plan",
        select_plan: "Select Plan",
        upgrade_scheduled: "Upgrade (scheduled)",
        downgrade_scheduled: "Downgrade (scheduled)",
        plan_already_scheduled: "Plan already scheduled",
        trial_ends_in_plural: "Trial ends in {days} days!",
        trial_ends_in_singular: "Trial ends in {days} day!",
        trial_period_days: "Trial period — {days} days left",
        select_plan_to_avoid_break: "Select a plan now to avoid service interruption.",
        try_all_features_free: "Try all features for free. Select a plan when you are ready.",
        appointment_created_assigned: "Appointment created and assigned to {name}",
        appointment_slot_created: "Appointment slot created! Clients can now book it.",
        up_to: "up to",
        error_loading_billing: "Error loading billing data",
        manage_subscription_limits: "Manage subscription and limits",
        downgrade_scheduled_msg: "Downgrade to {plan} scheduled for the next billing cycle.",
        loading_workout: "Loading workout...",
        no_participants: "No participants",
        choose_trainee: "Who are you training?",
        tap_to_log: "Tap to start logging",
        error_loading_requests: "Error loading requests",
        client_approved: "Client approved",
        plan_limit_reached: "Plan limit reached — upgrade to add more clients",
        request_rejected: "Request rejected",
        approve_or_reject_requests: "Approve or reject join requests",
        reject: "Reject",
        too_many_clients: "Too many clients",
        back_to_dashboard: "Back to Dashboard",
        activated: "activated",
        too_many_clients_for_plan: "Too many clients for this plan",
        reduce_clients_before_downgrade: "Reduce client count before downgrading",
        not_an_upgrade: "Selected plan is not an upgrade",
        pick_date: "Pick a date",
        pick_time: "Pick a time",
        no_participants_desc: "This session currently has no participants.",
        error_canceling_session: "Error canceling session",
        cancellation_failed: "Cancellation failed",
        term_deleted: "Session deleted",
        not_provided: "Not provided",
        list: "List",
        all_groups: "All Groups",
        add_to_program: "Add to program",
        new_program: "New Program",
        edit_program: "Edit Program",
    },
    Serbian: {
        dashboard: "Kontrolna tabla",
        history: "Istorija",
        profile: "Profil",
        settings: "Podešavanja",
        theme: "Tema",
        language: "Jezik",
        workout_history: "Istorija treninga",
        sessions: "Treninzi",
        exercises: "Vežbe",
        programs: "Programi",
        clients: "Klijenti",
        logout: "Odjavi se",
        light: "Svetla",
        dark: "Tamna",
        system_settings: "Sistemska podešavanja",
        save: "Sačuvaj",
        finish: "Završi",
        trainer_access: "Pristup za trenere",
        trainer_dashboard: "Kontrolna tabla trenera",
        manage_sessions: "Upravljajte svojim terminima",
        weekly_schedule: "Nedeljni raspored",
        to_rate: "Za ocenjivanje",
        nothing_to_rate: "Nema termina za ocenu",
        rate_participants: "Oceni učesnike",
        work_hours: "Radni sati",
        active_participants: "Aktivni učesnici",
        this_week: "Ove nedelje",
        total_scheduled: "Ukupno zakazano",
        loading: "Učitavanje",
        search_exercises: "Pretraži vežbe...",
        filter_category: "Filtriraj kategoriju",
        add_exercise: "Dodaj vežbu",
        training_programs: "Programi treninga",
        build_and_manage: "Kreiraj i upravljaj rutinama",
        all_clients: "Svi klijenti",
        create_program: "Kreiraj program",
        pick_exercise: "Izaberi vežbu...",
        difficulty: "Težina",
        beginner: "Početni",
        intermediate: "Srednji",
        advanced: "Napredni",
        title: "Naslov",
        description: "Opis",
        update: "Ažuriraj",
        assign_to_client: "Dodeli klijentu",
        assigned_to: "Dodeljeno",
        no_clients_assigned: "Još uvek nema dodeljenih klijenata",
        add_more: "Dodaj još",
        pick_client: "Izaberi klijenta...",
        confirm_assignment: "Potvrdi dodelu",
        rest_s: "Pauza (s)",
        tempo: "Tempo",
        sets: "Serije",
        reps: "Ponavljanja",
        search_programs: "Pretraži programe...",
        client_dashboard: "Kontrolna tabla klijenta",
        client_dashboard_subtitle: "Vaš nedeljni pregled i napredak",
        completed_total: "Ukupno završeno",
        avg_rating: "Prosečna ocena",
        out_of_10: "Od 10",
        scheduled: "Zakazano",
        ratings_trend: "Trend ocena",
        recent_sessions: "Nedavni treninzi",
        no_data_yet: "Još nema podataka",
        no_recent_sessions: "Nema nedavnih treninga",
        rating: "Ocena",
        cancel_session_confirm: "Da li ste sigurni da želite da otkažete ovaj termin?",
        session_canceled: "Termin otkazan",
        search_clients: "Pretraži klijente...",
        view_profile: "Pogledaj profil",
        progress: "Napredak",
        no_results: "Nema rezultata",
        public: "Javno",
        private: "Privatno",
        session: "Trening",
        loading_sessions: "Učitavanje treninga...",
        no_sessions_found: "Nema pronađenih treninga",
        no_programs_assigned: "Nema dodeljenih programa",
        email: "Email",
        gender: "Pol",
        age: "Godište",
        assigned_programs: "Dodeljeni programi",
        loading_history: "Učitavanje istorije...",
        history_subtitle: "Pregledajte svoje prošle performanse i pratite svoj napredak.",
        no_sessions_recorded: "Nema zabeleženih treninga",
        no_sessions_recorded_subtitle: "Završite svoj prvi trening sa trenerom da biste videli svoje zapise ovde!",
        set: "Serija",
        session_details: "Detalji termina",
        program: "Program",
        date: "Datum",
        time: "Vreme",
        type: "Tip",
        trainer: "Trener",
        client: "Klijent",
        close: "Zatvori",
        delete_session: "Obriši termin",
        start_workout: "Započni trening",
        not_assigned_yet: "Nije još dodeljeno",
        no_scheduled_sessions: "Nema zakazanih treninga za ovu nedelju.",
        group: "Grupni",
        individual: "Individualni",
        cancel: "Otkaži",
        failed_to_load_history: "Neuspešno učitavanje istorije",
        all_time: "Sav period",
        this_month: "Ovaj mesec",
        all_programs: "Svi programi",
        download_pdf: "Preuzmi PDF",
        member_menu: "Korisnički meni",
        trainer_menu: "Trenerov meni",
        certified_trainer: "Sertifikovani trener",
        sessions_completed: "Završenih treninga",
        total_programs: "Ukupno programa",
        total_hours: "Ukupno sati",

        // Public Nav
        nav_home: "Početna",
        nav_about: "O nama",
        nav_guide: "Vodič",
        nav_contact: "Kontakt",
        nav_login: "PRIJAVA",
        nav_register: "REGISTRACIJA",
        register_now: "Registruj se",

        // App Nav
        nav_dashboard: "Kontrolna tabla",
        nav_sessions: "Treninzi",
        nav_programs: "Programi",
        nav_clients: "Klijenti",
        nav_exercises: "Vežbe",
        nav_profile: "Profil",
        nav_logout: "Odjavi se",
        nav_history: "Istorija",

        personal_info: "Lične informacije",
        first_name: "Ime",
        last_name: "Prezime",
        male: "Muško",
        female: "Žensko",
        address: "Adresa",
        edit_profile: "Izmeni profil",
        save_changes: "Sačuvaj izmene",
        saving: "Čuvanje...",
        enter_first_name: "Unesite ime",
        enter_last_name: "Unesite prezime",
        select: "Izaberi...",
        date_of_birth: "Datum rođenja",
        reset_change_password: "Resetuj / Promeni lozinku",
        account_blocked_msg: "Nalog je blokiran — funkcionalnost je ograničena",
        profile_load_failed: "Profil nije mogao biti učitan.",
        edit: "Izmeni",
        exercise_library: "Biblioteka vežbi",
        manage_movements: "Upravljajte svojim pokretima",
        new_exercise: "Nova vežba",
        exercise_name: "Naziv vežbe",
        technique_cues: "Tehnički detalji...",
        muscle: "Mišić",
        equipment: "Oprema",
        client_progress: "Napredak Klijenta",
        total_workouts: "Ukupno Treninga",
        total_volume: "Ukupna Težina",
        exercises_tracked: "Praćene Vežbe",
        max_weight: "Maks. Težina",
        max_weight_kg: "Maks. Težina (kg)",
        total_volume_kg: "Ukupna Težina (kg)",
        client_profile: "Profil Klijenta",
        id: "ID",
        showing_last_5: "Prikazano poslednjih 5 treninga",
        live_workout: "Trening Uživo",
        who_training: "Koga trenirate?",
        select_participant: "Izaberite učesnika",
        tap_to_start: "Dodirnite da započnete",
        change: "Izmeni",
        add_set: "Dodaj seriju",
        finish_workout: "Završi trening",
        workout_saved: "Trening uspešno sačuvan!",
        error_saving_workout: "Greška pri čuvanju treninga",
        no_participants_msg: "Ovaj termin trenutno nema učesnika.",
        weight_kg: "Težina (kg)",
        analysis: "Analiza",
        volume: "Težina",
        level: "Nivo",
        video_url: "Video URL",
        save_exercise: "Sačuvaj vežbu",
        edit_exercise: "Izmeni vežbu",
        delete_exercise_confirm: "Da li ste sigurni da želite da obrišete ovu vežbu?",
        no_description: "Nema opisa",
        no_exercises_found: "Nema pronađenih vežbi",
        bench_press: "npr. Benč Pres",
        participant: "učesnik",
        participants: "učesnika",
        full_body: "Celo telo",
        chest: "Grudi",
        back: "Leđa",
        legs: "Noge",
        shoulders: "Ramena",
        arms: "Ruke",
        core: "Jezgro",
        cardio: "Kardio",
        mobility: "Mobilnost",
        none: "Bez opreme",
        bodyweight: "Sopstvena težina",
        dumbbells: "Bučice",
        barbell: "Šipka",
        kettlebell: "Kvibela",
        machine: "Mašina",
        bands: "Gume",
        other: "Ostalo",
        training_schedule: "Raspored treninga",
        manage_sessions_bookings: "Upravljajte terminima i rezervacijama",
        create_new_session: "Kreiraj novi termin",
        upcoming_sessions: "Predstojeći termini",
        pick_date_time: "Izaberite datum i vreme",
        capacity: "Kapacitet",
        duration_min: "Trajanje (minuti)",
        individual_tip: "Individualni treninzi automatski imaju kapacitet 1.",
        no_sessions_scheduled: "Nema zakazanih termina",
        awaiting_booking: "Čeka rezervaciju",
        no_program_yet: "Još nema programa",
        confirm_cancel_term: "Da li ste sigurni da želite da otkažete ovaj termin?",
        term_created: "Termin kreiran! Klijenti sada mogu da rezervišu.",
        term_canceled: "Termin otkazan",
        browse_book_sessions: "Pregledajte i rezervišite termine",
        filter_search: "Filter i pretraga",
        all_types: "Svi tipovi",
        all_sessions: "Svi termini",
        free: "Slobodan",
        full: "Popunjen",
        enrolled: "Prijavljen",
        book: "Rezerviši",
        booking: "Rezervacija",
        canceling: "Otkazivanje",
        not_cancellable: "Ne može se otkazati",
        no_sessions_found_msg: "Nema pronađenih termina",
        try_adjusting_filters: "Pokušajte da podesite filtere",
        search_sessions: "Pretraži termine...",
        session_booked: "Termin rezervisan",
        booking_failed: "Rezervacija neuspešna",
        my_programs: "Moji programi",
        programs_of_trainer: "Programi vašeg trenera",
        no_trainer_assigned: "Nema dodeljenog trenera",
        select_trainer_msg: "Izaberite trenera da vidite njihove programe.",
        all_levels: "Svi nivoi",
        apply: "Primeni",
        view_details: "Pogledaj detalje",
        author: "Autor",
        loading_programs: "Učitavanje programa",
        no_programs_found_msg: "Nema programa za zadate filtere.",
        no_programs_for_you: "Trener trenutno nema programa za vas.",
        try_adjusting_search: "Pokušajte drugu pretragu ili nivo.",
        loading_profile: "Učitavanje profila",
        choose_trainer: "Izaberite trenera",
        pick_trainer_subtitle: "Izaberite trenera da otključate termine i programe",
        no_trainers_available: "Nema dostupnih trenera",
        selecting: "Biranje",
        create_session: "Kreiraj termin",
        notes: "Napomene",
        position: "Pozicija",
        delete_program: "Obriši program",
        delete_program_confirm: "Da li ste sigurni da želite da obrišete ovaj program?",
        program_deleted: "Program obrisan",
        program_saved: "Program sačuvan",
        move_up: "Pomeri gore",
        move_down: "Pomeri dole",
        remove: "Ukloni",

        // Billing / Plans
        change_plan: "Promeni plan",
        plan: "Plan",
        pending: "Zakazano",
        pending_requests: "Zahtevi klijenata",
        pending_msg: "Zakazana promena na paket:",
        price: "Cena",
        next_renewal: "Sledeća obnova",
        no_plan_found: "Nema aktivne pretplate.",
        client_count: "Klijenti",
        billing_status: "Status naplate",
        trial_end: "Kraj trial-a",
        month: "mesec",
        activate: "Aktiviraj",
        current: "Aktivan",
        downgrade: "Downgrade",
        upgrade: "Upgrade",
        activate_plan_note: "Obnavlja se mesečno na datum aktivacije.",
        using_clients: "Koristiš {current} od {max} slotova za klijente",
        unlimited: "Neograničeno",
        your_plan: "Tvoj plan",
        active_plan: "Aktivan plan",
        pending_plan_change: "Zakazana promena paketa",
        no_pending_requests: "Nema novih zahteva.",
        approve: "Odobri",
        sign_up: "Registruj se",
        trainer_signup_note: "Treneri: pošaljite ime, prezime, email i link ka profilu na mreži (Instagram/LinkedIn) radi potvrde da ste trener.",
        client_signup_note: "Ova registracija je samo za klijente. Trenerski nalozi se otvaraju preko kontakt forme uz verifikaciju administratora.",
        create_client: "Kreiraj klijenta",
        create_client_account: "Kreiraj nalog klijenta",
        password: "Lozinka",
        birth_date: "Datum rođenja",
        enter_name: "Unesite ime",
        enter_surname: "Unesite prezime",
        creating_account: "Kreiranje naloga...",
        success_create_client: "Nalog klijenta je uspešno kreiran",
        failed_create_client: "Neuspešno kreiranje naloga",
        error_create_client: "Greška pri kreiranju naloga",
        fill_details_below: "Popunite detalje ispod",
        billing_and_plans: "NAPLATA I PAKETI",
        subscription_overview: "Pregled pretplate",
        available_plans: "Dostupni paketi",
        account_not_active: "Nalog nije aktivan",
        select_plan_to_continue: "Odaberi paket da nastaviš koristiti TrainMeter.",
        overview: "Pregled",
        client_requests_title: "ZAHTEVI KLIJENATA",
        no_new_requests: "Nema novih zahteva",
        client_request_empty_desc: "Kada klijent pošalje zahtev, videćeš ga ovde.",
        trial: "Trial",
        active: "Aktivan",
        past_due: "Isteklo",
        suspended: "Suspendovan",
        inactive: "Neaktivan",
        current_plan: "Trenutni paket",
        select_plan: "Odaberi paket",
        upgrade_scheduled: "Upgrade (zakazano)",
        downgrade_scheduled: "Downgrade (zakazano)",
        plan_already_scheduled: "Već ima zakazan plan",
        trial_ends_in_plural: "Trial ističe za {days} dana!",
        trial_ends_in_singular: "Trial ističe za {days} dan!",
        trial_period_days: "Trial period — još {days} dana",
        select_plan_to_avoid_break: "Odaberi paket odmah da izbegneš prekid usluge.",
        try_all_features_free: "Isprobaj sve funkcionalnosti besplatno. Odaberi paket kada budeš spreman.",
        appointment_created_assigned: "Termin kreiran i dodeljen klijentu {name}",
        appointment_slot_created: "Termin kreiran! Klijenti ga sada mogu rezervisati.",
        up_to: "do",
        error_loading_billing: "Greška pri učitavanju billing podataka",
        manage_subscription_limits: "Upravljaj pretplatom i limitima",
        downgrade_scheduled_msg: "Smanjenje na {plan} zakazano za sledeći obračunski ciklus.",
        loading_workout: "Učitavanje treninga...",
        no_participants: "Nema učesnika",
        choose_trainee: "Koga treniraš?",
        tap_to_log: "Dodirni da započneš logovanje",
        error_loading_requests: "Greška pri učitavanju zahteva",
        client_approved: "Klijent odobren",
        plan_limit_reached: "Dostignut limit paketa — nadogradi za više klijenata",
        request_rejected: "Zahtev odbijen",
        approve_or_reject_requests: "Odobri ili odbij zahteva za pridruživanje",
        reject: "Odbij",
        too_many_clients: "Previše klijenata",
        back_to_dashboard: "Nazad na kontrolnu tablu",
        activated: "aktiviran",
        too_many_clients_for_plan: "Previše klijenata za ovaj paket",
        reduce_clients_before_downgrade: "Smanji broj klijenata pre downgrade-a",
        not_an_upgrade: "Odabrani paket nije upgrade",
        pick_date: "Izaberi datum",
        pick_time: "Izaberi vreme",
        no_participants_desc: "Ovaj termin trenutno nema učesnika.",
        error_canceling_session: "Greška pri otkazivanju termina",
        cancellation_failed: "Otkazivanje nije uspelo",
        term_deleted: "Termin obrisan",
        not_provided: "Nije uneto",
        list: "Lista",
        all_groups: "Sve grupe",
        add_to_program: "Dodaj u program",
        new_program: "Novi program",
        edit_program: "Izmeni program",
    },
    Russian: {
        dashboard: "Панель управления",
        history: "История",
        profile: "Профиль",
        settings: "Настройки",
        theme: "Тема",
        language: "Язык",
        workout_history: "История тренировок",
        sessions: "Занятия",
        exercises: "Упражнения",
        programs: "Программы",
        clients: "Клиенты",
        logout: "Выйти",
        light: "Светлая",
        dark: "Темная",
        system_settings: "Системные настройки",
        save: "Сохранить",
        finish: "Завершить",
        trainer_access: "Доступ для тренеров",
        trainer_dashboard: "Панель тренера",
        manage_sessions: "Управляйте своими занятиями",
        weekly_schedule: "Еженедельное расписание",
        to_rate: "К оценке",
        nothing_to_rate: "Нечего оценивать",
        rate_participants: "Оценить участников",
        work_hours: "Рабочие часы",
        active_participants: "Активные участники",
        this_week: "На этой неделе",
        total_scheduled: "Всего запланировано",
        loading: "Загрузка",
        search_exercises: "Поиск упражнений...",
        filter_category: "Фильтр категорий",
        add_exercise: "Добавить упражнение",
        training_programs: "Программы тренировок",
        build_and_manage: "Создавайте и управляйте программами",
        all_clients: "Все клиенты",
        create_program: "Создать программу",
        pick_exercise: "Выберите упражнение...",
        difficulty: "Сложность",
        beginner: "Новичок",
        intermediate: "Средний",
        advanced: "Продвинутый",
        title: "Название",
        description: "Описание",
        update: "Обновить",
        assign_to_client: "Назначить клиенту",
        assigned_to: "Назначено",
        no_clients_assigned: "Клиенты еще не назначены",
        add_more: "Добавить еще",
        pick_client: "Выберите клиента...",
        confirm_assignment: "Подтвердить назначение",
        rest_s: "Отдых (с)",
        tempo: "Темп",
        sets: "Подходы",
        reps: "Повторения",
        search_programs: "Поиск программ...",
        client_dashboard: "Панель управления клиента",
        client_dashboard_subtitle: "Ваш еженедельный обзор и прогресс",
        completed_total: "Всего завершено",
        avg_rating: "Средняя оценка",
        out_of_10: "Из 10",
        scheduled: "Запланировано",
        ratings_trend: "Тренд оценок",
        recent_sessions: "Недавние тренировки",
        no_data_yet: "Данных пока нет",
        no_recent_sessions: "Нет недавних тренировок",
        rating: "Рейтинг",
        cancel_session_confirm: "Вы уверены, что хотите отменить это занятие?",
        session_canceled: "Занятие отменено",
        search_clients: "Поиск клиентов...",
        view_profile: "Просмотреть профиль",
        progress: "Прогресс",
        no_results: "Результатов не найдено",
        public: "Публичный",
        private: "Приватный",
        session: "Занятие",
        loading_sessions: "Загрузка занятий...",
        no_sessions_found: "Занятия не найдены",
        no_programs_assigned: "Программы не назначены",
        email: "Email",
        gender: "Пол",
        age: "Возраст",
        assigned_programs: "Назначенные программы",
        loading_history: "Загрузка вашей истории...",
        history_subtitle: "Просматривайте свои результаты и следите за прогрессом.",
        no_sessions_recorded: "Занятия еще не записаны",
        no_sessions_recorded_subtitle: "Завершите свое первое занятие с тренером, чтобы увидеть здесь свои записи!",
        set: "Подход",
        session_details: "Детали занятия",
        program: "Программа",
        date: "Дата",
        time: "Время",
        type: "Тип",
        trainer: "Тренер",
        client: "Клиент",
        close: "Закрыть",
        delete_session: "Удалить занятие",
        start_workout: "Начать тренировку",
        not_assigned_yet: "Еще не назначено",
        no_scheduled_sessions: "На эту неделю занятий не запланировано.",
        group: "Групповое",
        individual: "Индивидуальная",
        cancel: "Отмена",
        failed_to_load_history: "Не удалось загрузить историю",
        all_time: "За всё время",
        this_month: "Этот месяц",
        all_programs: "Все программы",
        download_pdf: "Скачать PDF",
        member_menu: "Меню участника",
        trainer_menu: "Меню тренера",
        certified_trainer: "Сертифицированный тренер",
        sessions_completed: "Завершено занятий",
        total_programs: "Всего программ",
        total_hours: "Всего часов",

        // Public Nav
        nav_home: "Главная",
        nav_about: "О нас",
        nav_guide: "Руководство",
        nav_contact: "Контакты",
        nav_login: "ВОЙТИ",
        nav_register: "РЕГИСТРАЦИЯ",
        register_now: "Зарегистрироваться",

        // App Nav
        nav_dashboard: "Панель",
        nav_sessions: "Тренировки",
        nav_programs: "Программы",
        nav_clients: "Клиенты",
        nav_exercises: "Упражнения",
        nav_profile: "Профиль",
        nav_logout: "Выйти",
        nav_history: "История",

        personal_info: "Личная информация",
        first_name: "Имя",
        last_name: "Фамилия",
        male: "Мужской",
        female: "Женский",
        address: "Адрес",
        edit_profile: "Редактировать профиль",
        save_changes: "Сохранить изменения",
        saving: "Сохранение...",
        enter_first_name: "Введите имя",
        enter_last_name: "Введите фамилию",
        select: "Выбрать...",
        date_of_birth: "Дата рождения",
        reset_change_password: "Сбросить / Изменить пароль",
        account_blocked_msg: "Аккаунт заблокирован — функциональность ограничена",
        profile_load_failed: "Не удалось загрузить профиль.",
        edit: "Редактировать",
        exercise_library: "Библиотека упражнений",
        manage_movements: "Управляйте своими движениями",
        new_exercise: "Новое упражнение",
        exercise_name: "Название упражнения",
        technique_cues: "Технические приемы...",
        muscle: "Мышца",
        equipment: "Оборудование",
        client_progress: "Прогресс клиента",
        total_workouts: "Всего тренировок",
        total_volume: "Общий объем",
        exercises_tracked: "Отслеживаемых упражнений",
        max_weight: "Макс. вес",
        max_weight_kg: "Макс. вес (кг)",
        total_volume_kg: "Общий объем (кг)",
        client_profile: "Профиль клиента",
        id: "ID",
        showing_last_5: "Показано последние 5 тренировок",
        live_workout: "Живая тренировка",
        who_training: "Кого вы тренируете?",
        select_participant: "Выберите участника",
        tap_to_start: "Нажмите, чтобы начать",
        change: "Изменить",
        add_set: "Добавить сет",
        finish_workout: "Завершить тренировку",
        workout_saved: "Тренировка успешно сохранена!",
        error_saving_workout: "Ошибка при сохранении тренировки",
        no_participants_msg: "На этом занятии пока нет участников.",
        weight_kg: "Вес (кг)",
        analysis: "Анализ",
        volume: "Объем",
        level: "Уровень",
        video_url: "Ссылка на видео",
        save_exercise: "Сохранить упражнение",
        edit_exercise: "Изменить упражнение",
        delete_exercise_confirm: "Вы уверены, что хотите удалить это упражнение?",
        no_description: "Нет описания",
        no_exercises_found: "Упражнения не найдены",
        bench_press: "например, Жим лежа",
        participant: "участник",
        participants: "участника",
        full_body: "Все тело",
        chest: "Грудь",
        back: "Спина",
        legs: "Ноги",
        shoulders: "Плечи",
        arms: "Руки",
        core: "Корпус",
        cardio: "Кардио",
        mobility: "Мобильность",
        none: "Без оборудования",
        bodyweight: "Собственный вес",
        dumbbells: "Гантели",
        barbell: "Штанга",
        kettlebell: "Гиря",
        machine: "Тренажер",
        bands: "Резинки",
        other: "Другое",
        training_schedule: "Расписание тренировок",
        manage_sessions_bookings: "Управляйте занятиями и бронированием",
        create_new_session: "Создать новое занятие",
        upcoming_sessions: "Предстоящие занятия",
        pick_date_time: "Выберите дату и время",
        capacity: "Вместимость",
        duration_min: "Продолжительность (мин)",
        individual_tip: "Индивидуальные занятия автоматически имеют вместимость 1.",
        no_sessions_scheduled: "Нет запланированных занятий",
        awaiting_booking: "Ожидание бронирования",
        no_program_yet: "Программа ещё не назначена",
        confirm_cancel_term: "Вы уверены, что хотите отменить это занятие?",
        term_created: "Слот создан! Клиенты могут бронировать.",
        term_canceled: "Занятие отменено",
        browse_book_sessions: "Просмотр и бронирование занятий",
        filter_search: "Фильтр и поиск",
        all_types: "Все типы",
        all_sessions: "Все занятия",
        free: "Свободно",
        full: "Заполнено",
        enrolled: "Записан",
        book: "Забронировать",
        booking: "Бронирование",
        canceling: "Отмена",
        not_cancellable: "Нельзя отменить",
        no_sessions_found_msg: "Занятия не найдены",
        try_adjusting_filters: "Попробуйте изменить фильтры",
        search_sessions: "Поиск занятий...",
        session_booked: "Занятие забронировано",
        booking_failed: "Бронирование не удалось",
        my_programs: "Мои программы",
        programs_of_trainer: "Программы вашего тренера",
        no_trainer_assigned: "Тренер не назначен",
        select_trainer_msg: "Выберите тренера, чтобы увидеть его программы.",
        all_levels: "Все уровни",
        apply: "Применить",
        view_details: "Подробнее",
        author: "Автор",
        loading_programs: "Загрузка программ",
        no_programs_found_msg: "Программы не найдены.",
        no_programs_for_you: "У тренера пока нет программ для вас.",
        try_adjusting_search: "Попробуйте другой поиск или уровень.",
        loading_profile: "Загрузка профиля",
        choose_trainer: "Выберите тренера",
        pick_trainer_subtitle: "Выберите тренера для доступа к занятиям и программам",
        no_trainers_available: "Нет доступных тренеров",
        selecting: "Выбор",
        create_session: "Создать занятие",
        notes: "Заметки",
        position: "Позиция",
        delete_program: "Удалить программу",
        delete_program_confirm: "Вы уверены, что хотите удалить эту программу?",
        program_deleted: "Программа удалена",
        program_saved: "Программа сохранена",
        move_up: "Вверх",
        move_down: "Вниз",
        remove: "Убрать",

        // Billing / Plans
        change_plan: "Сменить план",
        plan: "План",
        pending: "Ожидание",
        pending_requests: "Запросы клиентов",
        pending_msg: "Запланирована смена на план:",
        price: "Цена",
        next_renewal: "Следующее продление",
        no_plan_found: "Нет активной подписки.",
        client_count: "Клиенты",
        billing_status: "Статус оплаты",
        trial_end: "Конец триала",
        month: "месяц",
        activate: "Активировать",
        current: "Текущий",
        downgrade: "Понизить",
        upgrade: "Повысить",
        activate_plan_note: "Продлевается ежемесячно в дату активации.",
        using_clients: "Используете {current} из {max} слотов для клиентов",
        unlimited: "Без ограничений",
        your_plan: "Ваш план",
        active_plan: "Активный план",
        pending_plan_change: "Запланированная смена плана",
        no_pending_requests: "Нет новых запросов.",
        approve: "Одобрить",
        sign_up: "Регистрация",
        trainer_signup_note: "Тренеры: отправьте имя, фамилию, email и ссылку на соцсеть (Instagram/LinkedIn) для подтверждения, что вы тренер.",
        client_signup_note: "Эта регистрация только для клиентов. Аккаунты тренеров создаются через контактную форму с проверкой администратора.",
        create_client: "Создать клиента",
        create_client_account: "Создать аккаунт клиента",
        password: "Пароль",
        birth_date: "Дата рождения",
        enter_name: "Введите имя",
        enter_surname: "Введите фамилию",
        creating_account: "Создание аккаунта...",
        success_create_client: "Аккаунт клиента успешно создан",
        failed_create_client: "Не удалось создать аккаунт",
        error_create_client: "Ошибка при создании аккаунта",
        fill_details_below: "Заполните детали ниже",
        billing_and_plans: "ОПЛАТА И ПЛАНЫ",
        subscription_overview: "Обзор подписки",
        available_plans: "Доступные планы",
        account_not_active: "Аккаунт не активен",
        select_plan_to_continue: "Выберите план, чтобы продолжить использование TrainMeter.",
        overview: "Обзор",
        client_requests_title: "ЗАПРОСЫ КЛИЕНТОВ",
        no_new_requests: "Нет новых запросов",
        client_request_empty_desc: "Когда клиент отправит запрос, вы увидите его здесь.",
        trial: "Пробный период",
        active: "Активен",
        past_due: "Просрочен",
        suspended: "Приостановлен",
        inactive: "Неактивен",
        current_plan: "Текущий план",
        select_plan: "Выбрать план",
        upgrade_scheduled: "Обновление (запланировано)",
        downgrade_scheduled: "Понижение (запланировано)",
        plan_already_scheduled: "План уже запланирован",
        trial_ends_in_plural: "Пробный период истекает через {days} дней!",
        trial_ends_in_singular: "Пробный период истекает через {days} день!",
        trial_period_days: "Пробный период — осталось {days} дней",
        select_plan_to_avoid_break: "Выберите план сейчас, чтобы избежать перерыва в обслуживании.",
        try_all_features_free: "Попробуйте все функции бесплатно. Выберите план, когда будете готовы.",
        appointment_created_assigned: "Запись создана и назначена клиенту {name}",
        appointment_slot_created: "Слот записи создан! Клиенты теперь могут его забронировать.",
        up_to: "до",
        error_loading_billing: "Ошибка загрузки данных биллинга",
        manage_subscription_limits: "Управление подпиской и лимитами",
        downgrade_scheduled_msg: "Понижение до {plan} запланировано на следующий цикл.",
        loading_workout: "Загрузка тренировки...",
        no_participants: "Нет участников",
        choose_trainee: "Кого вы тренируете?",
        tap_to_log: "Нажмите, чтобы начать запись",
        error_loading_requests: "Ошибка загрузки запросов",
        client_approved: "Клиент одобрен",
        plan_limit_reached: "Лимит плана достигнут — обновите план",
        request_rejected: "Запрос отклонен",
        approve_or_reject_requests: "Одобрить или отклонить запросы",
        reject: "Отклонить",
        too_many_clients: "Слишком много клиентов",
        back_to_dashboard: "Вернуться на панель",
        activated: "активирован",
        too_many_clients_for_plan: "Слишком много клиентов для этого плана",
        reduce_clients_before_downgrade: "Уменьшите количество клиентов перед понижением",
        not_an_upgrade: "Выбранный план не является обновлением",
        pick_date: "Выберите дату",
        pick_time: "Выберите время",
        no_participants_desc: "На эту сессию пока нет участников.",
        error_canceling_session: "Ошибка отмены занятия",
        cancellation_failed: "Ошибка отмены",
        term_deleted: "Занятие удалено",
        not_provided: "Не указано",
        list: "Список",
        all_groups: "Все группы",
        add_to_program: "Добавить в программу",
        new_program: "Новая программа",
        edit_program: "Редактировать программу",
    },
    German: {
        dashboard: "Dashboard",
        history: "Verlauf",
        profile: "Profil",
        settings: "Einstellungen",
        theme: "Thema",
        language: "Sprache",
        workout_history: "Trainingsverlauf",
        sessions: "Sitzungen",
        exercises: "Übungen",
        programs: "Programme",
        clients: "Kunden",
        logout: "Abmelden",
        light: "Hell",
        dark: "Dunkel",
        system_settings: "Systemeinstellungen",
        save: "Speichern",
        finish: "Beenden",
        trainer_access: "Trainer-Zugang",
        trainer_dashboard: "Trainer-Dashboard",
        manage_sessions: "Verwalten Sie Ihre Sitzungen",
        weekly_schedule: "Wochenplan",
        to_rate: "Zu bewerten",
        nothing_to_rate: "Nichts zu bewerten",
        rate_participants: "Teilnehmer bewerten",
        work_hours: "Arbeitsstunden",
        active_participants: "Aktive Teilnehmer",
        this_week: "Diese Woche",
        total_scheduled: "Insgesamt geplant",
        loading: "Laden",
        search_exercises: "Übungen suchen...",
        filter_category: "Kategorie filtern",
        add_exercise: "Übung hinzufügen",
        training_programs: "Trainingsprogramme",
        build_and_manage: "Routinen erstellen und verwalten",
        all_clients: "Alle Kunden",
        create_program: "Programm erstellen",
        pick_exercise: "Übung auswählen...",
        difficulty: "Schwierigkeit",
        beginner: "Anfänger",
        intermediate: "Fortgeschritten",
        advanced: "Profi",
        title: "Titel",
        description: "Beschreibung",
        update: "Aktualisieren",
        assign_to_client: "Kunden zuweisen",
        assigned_to: "Zugewiesen an",
        no_clients_assigned: "Noch keine Kunden zugewiesen",
        add_more: "Mehr hinzufügen",
        pick_client: "Kunden auswählen...",
        confirm_assignment: "Zuweisung bestätigen",
        rest_s: "Pause (s)",
        tempo: "Tempo",
        sets: "Sätze",
        reps: "Wiederholungen",
        search_programs: "Programme suchen...",
        client_dashboard: "Kunden-Dashboard",
        client_dashboard_subtitle: "Ihre wöchentliche Übersicht & Fortschritt",
        completed_total: "Gesamt abgeschlossen",
        avg_rating: "Durchschnittliche Bewertung",
        out_of_10: "Von 10",
        scheduled: "Geplant",
        ratings_trend: "Bewertungstrend",
        recent_sessions: "Letzte Sitzungen",
        no_data_yet: "Noch keine Daten",
        no_recent_sessions: "Keine letzten Sitzungen",
        rating: "Bewertung",
        cancel_session_confirm: "Sind Sie sicher, dass Sie diese Sitzung absagen möchten?",
        session_canceled: "Sitzung abgesagt",
        search_clients: "Kunden suchen...",
        view_profile: "Profil anzeigen",
        progress: "Fortschritt",
        no_results: "Keine Ergebnisse gefunden",
        public: "Öffentlich",
        private: "Privat",
        session: "Sitzung",
        loading_sessions: "Sitzungen werden geladen...",
        no_sessions_found: "Keine Sitzungen gefunden",
        no_programs_assigned: "Keine Programme zugewiesen",
        email: "Email",
        gender: "Geschlecht",
        age: "Alter",
        assigned_programs: "Zugewiesene Programme",
        loading_history: "Lade deinen Verlauf...",
        history_subtitle: "Überprüfe deine bisherige Leistung und verfolge dein Wachstum.",
        no_sessions_recorded: "Noch keine Sitzungen aufgezeichnet",
        no_sessions_recorded_subtitle: "Schließe deine erste Sitzung mit deinem Trainer ab, um hier deine Logs zu sehen!",
        set: "Satz",
        session_details: "Sitzungsdetails",
        program: "Programm",
        date: "Datum",
        time: "Zeit",
        type: "Typ",
        trainer: "Trainer",
        client: "Kunde",
        close: "Schließen",
        delete_session: "Sitzung löschen",
        start_workout: "Training starten",
        not_assigned_yet: "Noch nicht zugewiesen",
        no_scheduled_sessions: "Keine geplanten Sitzungen für diese Woche.",
        group: "Gruppe",
        individual: "Individuell",
        cancel: "Abbrechen",
        failed_to_load_history: "Verlauf konnte nicht geladen werden",
        all_time: "Gesamter Zeitraum",
        this_month: "Diesen Monat",
        all_programs: "Alle Programme",
        download_pdf: "PDF herunterladen",
        member_menu: "Mitgliedermenü",
        trainer_menu: "Trainermenü",
        certified_trainer: "Zertifizierter Trainer",
        sessions_completed: "Abgeschlossene Sitzungen",
        total_programs: "Gesamtprogramme",
        total_hours: "Gesamtstunden",

        // Public Nav
        nav_home: "Startseite",
        nav_about: "Über uns",
        nav_guide: "Leitfaden",
        nav_contact: "Kontakt",
        nav_login: "ANMELDEN",
        nav_register: "REGISTRIEREN",
        register_now: "Jetzt registrieren",

        // App Nav
        nav_dashboard: "Dashboard",
        nav_sessions: "Sitzungen",
        nav_programs: "Programme",
        nav_clients: "Kunden",
        nav_exercises: "Übungen",
        nav_profile: "Profil",
        nav_logout: "Abmelden",
        nav_history: "Verlauf",

        personal_info: "Persönliche Informationen",
        first_name: "Vorname",
        last_name: "Nachname",
        male: "Männlich",
        female: "Weiblich",
        address: "Adresse",
        edit_profile: "Profil bearbeiten",
        save_changes: "Änderungen speichern",
        saving: "Wird gespeichert...",
        enter_first_name: "Vornamen eingeben",
        enter_last_name: "Nachnamen eingeben",
        select: "Auswählen...",
        date_of_birth: "Geburtsdatum",
        reset_change_password: "Passwort zurücksetzen / ändern",
        account_blocked_msg: "Konto ist gesperrt — Funktionalität ist eingeschränkt",
        profile_load_failed: "Profil konnte nicht geladen werden.",
        edit: "Bearbeiten",
        exercise_library: "Übungsbibliothek",
        manage_movements: "Verwalten Sie Ihre Trainingsbewegungen",
        new_exercise: "Neue Übung",
        exercise_name: "Übungsname",
        technique_cues: "Technik-Hinweise...",
        muscle: "Muskel",
        equipment: "Ausrüstung",
        client_progress: "Klientenfortschritt",
        total_workouts: "Trainingseinheiten gesamt",
        total_volume: "Gesamtvolumen",
        exercises_tracked: "Verfolgte Übungen",
        max_weight: "Max. Gewicht",
        max_weight_kg: "Max. Gewicht (kg)",
        total_volume_kg: "Gesamtvolumen (kg)",
        client_profile: "Klientenprofil",
        id: "ID",
        showing_last_5: "Gezeigt letzte 5 Sitzungen",
        live_workout: "Live-Training",
        who_training: "Wen trainieren Sie?",
        select_participant: "Teilnehmer auswählen",
        tap_to_start: "Tippen, um zu starten",
        change: "Ändern",
        add_set: "Satz hinzufügen",
        finish_workout: "Training beenden",
        workout_saved: "Training erfolgreich gespeichert!",
        error_saving_workout: "Fehler beim Speichern des Trainings",
        no_participants_msg: "Diese Session hat momentan keine Teilnehmer.",
        weight_kg: "Gewicht (kg)",
        analysis: "Analyse",
        volume: "Volumen",
        level: "Niveau",
        video_url: "Video-URL",
        save_exercise: "Übung speichern",
        edit_exercise: "Übung bearbeiten",
        delete_exercise_confirm: "Sind Sie sicher, dass Sie diese Übung löschen möchten?",
        no_description: "Keine Beschreibung",
        no_exercises_found: "Keine Übungen gefunden",
        bench_press: "z.B. Bankdrücken",
        participant: "Teilnehmer",
        participants: "Teilnehmer",
        full_body: "Ganzkörper",
        chest: "Brust",
        back: "Rücken",
        legs: "Beine",
        shoulders: "Schultern",
        arms: "Arme",
        core: "Kern",
        cardio: "Cardio",
        mobility: "Mobilität",
        none: "Keine",
        bodyweight: "Eigengewicht",
        dumbbells: "Kurzhanteln",
        barbell: "Langhantel",
        kettlebell: "Kettlebell",
        machine: "Maschine",
        bands: "Bänder",
        other: "Andere",
        training_schedule: "Trainingsplan",
        manage_sessions_bookings: "Verwalten Sie Ihre Termine und Buchungen",
        create_new_session: "Neuen Termin erstellen",
        upcoming_sessions: "Bevorstehende Termine",
        pick_date_time: "Datum und Uhrzeit wählen",
        capacity: "Kapazität",
        duration_min: "Dauer (Minuten)",
        individual_tip: "Einzeltrainings haben automatisch eine Kapazität von 1.",
        no_sessions_scheduled: "Keine Termine geplant",
        awaiting_booking: "Wartet auf Buchung",
        no_program_yet: "Noch kein Programm",
        confirm_cancel_term: "Sind Sie sicher, dass Sie diesen Termin absagen möchten?",
        term_created: "Termin erstellt! Kunden können jetzt buchen.",
        term_canceled: "Termin abgesagt",
        browse_book_sessions: "Termine durchsuchen und buchen",
        filter_search: "Filtern & Suchen",
        all_types: "Alle Typen",
        all_sessions: "Alle Termine",
        free: "Frei",
        full: "Voll",
        enrolled: "Eingeschrieben",
        book: "Buchen",
        booking: "Buchung",
        canceling: "Stornierung",
        not_cancellable: "Nicht stornierbar",
        no_sessions_found_msg: "Keine Termine gefunden",
        try_adjusting_filters: "Versuchen Sie die Filter anzupassen",
        search_sessions: "Termine suchen...",
        session_booked: "Termin gebucht",
        booking_failed: "Buchung fehlgeschlagen",
        my_programs: "Meine Programme",
        programs_of_trainer: "Programme Ihres Trainers",
        no_trainer_assigned: "Kein Trainer zugewiesen",
        select_trainer_msg: "Wählen Sie einen Trainer, um deren Programme zu sehen.",
        all_levels: "Alle Stufen",
        apply: "Anwenden",
        view_details: "Details ansehen",
        author: "Autor",
        loading_programs: "Programme laden",
        no_programs_found_msg: "Keine Programme für die gewählten Filter gefunden.",
        no_programs_for_you: "Der Trainer hat derzeit keine Programme für Sie.",
        try_adjusting_search: "Versuchen Sie eine andere Suche oder Stufe.",
        loading_profile: "Profil wird geladen",
        choose_trainer: "Trainer wählen",
        pick_trainer_subtitle: "Wählen Sie einen Trainer, um Termine und Programme freizuschalten",
        no_trainers_available: "Keine Trainer verfügbar",
        selecting: "Auswählen",
        create_session: "Termin erstellen",
        notes: "Notizen",
        position: "Position",
        delete_program: "Programm löschen",
        delete_program_confirm: "Sind Sie sicher, dass Sie dieses Programm löschen möchten?",
        program_deleted: "Programm gelöscht",
        program_saved: "Programm gespeichert",
        move_up: "Nach oben",
        move_down: "Nach unten",
        remove: "Entfernen",

        // Billing / Plans
        change_plan: "Plan ändern",
        plan: "Plan",
        pending: "Geplant",
        pending_requests: "Client-Anfragen",
        pending_msg: "Geplanter Wechsel auf Plan:",
        price: "Preis",
        next_renewal: "Nächste Verlängerung",
        no_plan_found: "Kein aktives Abonnement.",
        client_count: "Kunden",
        billing_status: "Abrechnungsstatus",
        trial_end: "Ende der Testphase",
        month: "Monat",
        activate: "Aktivieren",
        current: "Aktiv",
        downgrade: "Downgrade",
        upgrade: "Upgrade",
        activate_plan_note: "Verlängert sich monatlich am Aktivierungsdatum.",
        using_clients: "Genutzt {current} von {max} Kundenslots",
        unlimited: "Unbegrenzt",
        your_plan: "Dein Plan",
        active_plan: "Aktiver Plan",
        pending_plan_change: "Geplanter Paketwechsel",
        no_pending_requests: "Keine offenen Anfragen.",
        approve: "Genehmigen",
        sign_up: "Registrieren",
        trainer_signup_note: "Trainer: Senden Sie Vor- und Nachnamen, E-Mail und einen Social-Link (Instagram/LinkedIn), um zu bestätigen, dass Sie Trainer sind.",
        client_signup_note: "Diese Registrierung ist nur für Kunden. Trainerkonten werden über das Kontaktformular mit Administratorprüfung erstellt.",
        create_client: "Kunde erstellen",
        create_client_account: "Kundenkonto erstellen",
        password: "Passwort",
        birth_date: "Geburtsdatum",
        enter_name: "Name eingeben",
        enter_surname: "Nachnamen eingeben",
        creating_account: "Konto wird erstellt...",
        success_create_client: "Kundenkonto erfolgreich erstellt",
        failed_create_client: "Kontoerstellung fehlgeschlagen",
        error_create_client: "Fehler bei der Kontoerstellung",
        fill_details_below: "Füllen Sie die Details unten aus",
        billing_and_plans: "ABRECHNUNG & PLÄNE",
        subscription_overview: "Abonnement-Übersicht",
        available_plans: "Verfügbare Pläne",
        account_not_active: "Konto ist nicht aktiv",
        select_plan_to_continue: "Wählen Sie einen Plan, um TrainMeter weiter zu nutzen.",
        overview: "Überblick",
        client_requests_title: "KUNDENANFRAGEN",
        no_new_requests: "Keine neuen Anfragen",
        client_request_empty_desc: "Wenn ein Kunde eine Anfrage sendet, sehen Sie diese hier.",
        trial: "Testversion",
        active: "Aktiv",
        past_due: "Überfällig",
        suspended: "Suspendiert",
        inactive: "Inaktiv",
        current_plan: "Aktueller Plan",
        select_plan: "Plan auswählen",
        upgrade_scheduled: "Upgrade (geplant)",
        downgrade_scheduled: "Downgrade (geplant)",
        plan_already_scheduled: "Plan bereits geplant",
        trial_ends_in_plural: "Testphase endet in {days} Tagen!",
        trial_ends_in_singular: "Testphase endet in {days} Tag!",
        trial_period_days: "Testzeitraum — noch {days} Tage",
        select_plan_to_avoid_break: "Wählen Sie jetzt einen Plan, um Serviceunterbrechungen zu vermeiden.",
        try_all_features_free: "Testen Sie alle Funktionen kostenlos. Wählen Sie einen Plan, wenn Sie bereit sind.",
        appointment_created_assigned: "Termin erstellt und {name} zugewiesen",
        appointment_slot_created: "Terminslot erstellt! Kunden können ihn jetzt buchen.",
        up_to: "bis zu",
        error_loading_billing: "Fehler beim Laden der Abrechnungsdaten",
        manage_subscription_limits: "Abonnement und Limits verwalten",
        downgrade_scheduled_msg: "Downgrade auf {plan} für den nächsten Abrechnungszyklus geplant.",
        loading_workout: "Workout wird geladen...",
        no_participants: "Keine Teilnehmer",
        choose_trainee: "Wen trainierst du?",
        tap_to_log: "Tippen, um die Protokollierung zu starten",
        error_loading_requests: "Fehler beim Laden der Anfragen",
        client_approved: "Kunde genehmigt",
        plan_limit_reached: "Plan-Limit erreicht — Upgrade erforderlich",
        request_rejected: "Anfrage abgelehnt",
        approve_or_reject_requests: "Beitrittsanfragen genehmigen oder ablehnen",
        reject: "Ablehnen",
        too_many_clients: "Zu viele Kunden",
        back_to_dashboard: "Zurück zum Dashboard",
        activated: "aktiviert",
        too_many_clients_for_plan: "Zu viele Kunden für diesen Plan",
        reduce_clients_before_downgrade: "Kundenanzahl vor dem Downgrade reduzieren",
        not_an_upgrade: "Der ausgewählte Plan ist kein Upgrade",
        pick_date: "Datum wählen",
        pick_time: "Zeit wählen",
        no_participants_desc: "Diese Session hat aktuell keine Teilnehmer.",
        error_canceling_session: "Fehler beim Absagen der Sitzung",
        cancellation_failed: "Absage fehlgeschlagen",
        term_deleted: "Sitzung gelöscht",
        not_provided: "Nicht angegeben",
        list: "Liste",
        all_groups: "Alle Gruppen",
        add_to_program: "Zum Programm hinzufügen",
        new_program: "Neues Programm",
        edit_program: "Programm bearbeiten",
    },
    Hungarian: {
        dashboard: "Vezérlőpult",
        history: "Előzmények",
        profile: "Profil",
        settings: "Beállítások",
        theme: "Téma",
        language: "Nyelv",
        workout_history: "Edzés előzmények",
        sessions: "Munkamenetek",
        exercises: "Gyakorlatok",
        programs: "Programok",
        clients: "Ügyfelek",
        logout: "Kijelentkezés",
        light: "Világos",
        dark: "Sötét",
        system_settings: "Rendszerbeállítások",
        save: "Mentés",
        finish: "Befejezés",
        trainer_access: "Edzői hozzáférés",
        trainer_dashboard: "Edzői irányítópult",
        manage_sessions: "Kezelje a munkameneteit",
        weekly_schedule: "Heti ütemterv",
        to_rate: "Értékelendő",
        nothing_to_rate: "Nincs értékelendő",
        rate_participants: "Résztvevők értékelése",
        work_hours: "Munkaórák",
        active_participants: "Aktív résztvevők",
        this_week: "Ezen a héten",
        total_scheduled: "Összesen ütemezve",
        loading: "Betöltés",
        search_exercises: "Gyakorlatok keresése...",
        filter_category: "Kategória szűrése",
        add_exercise: "Gyakorlat hozzáadása",
        training_programs: "Edzésprogramok",
        build_and_manage: "Rutinok létrehozása és kezelése",
        all_clients: "Összes ügyfél",
        create_program: "Program létrehozása",
        pick_exercise: "Gyakorlat kiválasztása...",
        difficulty: "Nehézség",
        beginner: "Kezdő",
        intermediate: "Középhaladó",
        advanced: "Haladó",
        title: "Cím",
        description: "Leírás",
        update: "Frissítés",
        assign_to_client: "Hozzárendelés ügyfélhez",
        assigned_to: "Hozzárendelve",
        no_clients_assigned: "Még nincs ügyfél hozzárendelve",
        add_more: "További hozzáadása",
        pick_client: "Ügyfél kiválasztása...",
        confirm_assignment: "Hozzárendelés megerősítése",
        rest_s: "Pihenő (mp)",
        tempo: "Tempó",
        sets: "Sorozatok",
        reps: "Ismétlések",
        search_programs: "Programok keresése...",
        client_dashboard: "Ügyfél irányítópult",
        client_dashboard_subtitle: "Heti áttekintés és fejlődés",
        completed_total: "Összesen befejezve",
        avg_rating: "Átlagos értékelés",
        out_of_10: "10-ből",
        scheduled: "Ütemezve",
        ratings_trend: "Értékelési trend",
        recent_sessions: "Legutóbbi edzések",
        no_data_yet: "Még nincs adat",
        no_recent_sessions: "Nincs legutóbbi edzés",
        rating: "Értékelés",
        cancel_session_confirm: "Biztosan törölni szeretné ezt az edzést?",
        session_canceled: "Edzés törölve",
        search_clients: "Ügyfelek keresése...",
        view_profile: "Profil megtekintése",
        progress: "Fejlődés",
        no_results: "Nincs találat",
        public: "Publikus",
        private: "Privát",
        session: "Edzés",
        loading_sessions: "Edzések betöltése...",
        no_sessions_found: "Nem található edzés",
        no_programs_assigned: "Nincs hozzárendelt program",
        email: "E-mail",
        gender: "Nem",
        age: "Kor",
        assigned_programs: "Hozzárendelt programok",
        loading_history: "Előzmények betöltése...",
        history_subtitle: "Tekintse át korábbi teljesítményét és kövesse nyomon fejlődését.",
        no_sessions_recorded: "Még nincs rögzített edzés",
        no_sessions_recorded_subtitle: "Végezze el az első edzését az edzőjével, hogy itt lássa a naplóit!",
        set: "Széria",
        session_details: "Edzés részletei",
        program: "Program",
        date: "Dátum",
        time: "Időpont",
        type: "Típus",
        trainer: "Edző",
        client: "Ügyfél",
        close: "Bezárás",
        delete_session: "Edzés törlése",
        start_workout: "Edzés indítása",
        not_assigned_yet: "Még nincs hozzárendelve",
        no_scheduled_sessions: "Nincs ütemezett edzés erre a hétre.",
        group: "Csoportos",
        individual: "Egyéni",
        cancel: "Mégse",
        failed_to_load_history: "Nem sikerült betölteni az előzményeket",
        all_time: "Teljes időszak",
        this_month: "Ez a hónap",
        all_programs: "Minden program",
        download_pdf: "PDF letöltése",
        member_menu: "Tagi menü",
        trainer_menu: "Edzői menü",
        certified_trainer: "Szakértő Edző",
        sessions_completed: "Befejezett Edzések",
        total_programs: "Összes Program",
        total_hours: "Összes Óra",

        // Public Nav
        nav_home: "Kezdőlap",
        nav_about: "Rólunk",
        nav_guide: "Útmutató",
        nav_contact: "Kapcsolat",
        nav_login: "BEJELENTKEZÉS",
        nav_register: "REGISZTRÁCIÓ",
        register_now: "Regisztrálj most",

        // App Nav
        nav_dashboard: "Kezelőpanel",
        nav_sessions: "Edzések",
        nav_programs: "Programok",
        nav_clients: "Ügyfelek",
        nav_exercises: "Gyakorlatok",
        nav_profile: "Profil",
        nav_logout: "Kijelentkezés",
        nav_history: "Előzmények",

        personal_info: "Személyes Információ",
        first_name: "Keresztnév",
        last_name: "Vezetéknév",
        male: "Férfi",
        female: "Nő",
        address: "Cím",
        edit_profile: "Profil Szerkesztése",
        save_changes: "Módosítások Mentése",
        saving: "Mentés...",
        enter_first_name: "Adja meg a keresztnevét",
        enter_last_name: "Adja meg a vezetéknevét",
        select: "Válasszon...",
        date_of_birth: "Születési Idő",
        reset_change_password: "Jelszó Visszaállítása / Módosítása",
        account_blocked_msg: "A fiók blokkolva van — a funkcionalitás korlátozott",
        profile_load_failed: "A profilt nem sikerült betölteni.",
        edit: "Szerkesztés",
        exercise_library: "Gyakorlat Tár",
        manage_movements: "Gyakorlatok kezelése",
        new_exercise: "Új Gyakorlat",
        exercise_name: "Gyakorlat Neve",
        technique_cues: "Technikai tippek...",
        muscle: "Izom",
        equipment: "Eszköz",
        client_progress: "Ügyfél Fejlődése",
        total_workouts: "Összes Edzés",
        total_volume: "Összes Súly",
        exercises_tracked: "Mért Gyakorlatok",
        max_weight: "Max. Súly",
        max_weight_kg: "Max. Súly (kg)",
        total_volume_kg: "Összes Súly (kg)",
        client_profile: "Ügyfél Profil",
        id: "ID",
        showing_last_5: "Az utolsó 5 edzés megjelenítése",
        live_workout: "Élő Edzés",
        who_training: "Kit edz most?",
        select_participant: "Résztvevő kiválasztása",
        tap_to_start: "Koppintson a kezdéshez",
        change: "Módosítás",
        add_set: "Széria hozzáadása",
        finish_workout: "Edzés befejezése",
        workout_saved: "Edzés sikeresen mentve!",
        error_saving_workout: "Hiba az edzés mentésekor",
        no_participants_msg: "Ennek az edzésnek jelenleg nincs résztvevője.",
        weight_kg: "Súly (kg)",
        analysis: "Elemzés",
        volume: "Súly",
        level: "Szint",
        video_url: "Videó URL",
        save_exercise: "Gyakorlat mentése",
        edit_exercise: "Gyakorlat szerkesztése",
        delete_exercise_confirm: "Biztosan törölni szeretné ezt a gyakorlatot?",
        no_description: "Nincs leírás",
        no_exercises_found: "Nincs találat",
        bench_press: "pl. Fekvenyomás",
        participant: "résztvevő",
        participants: "résztvevő",
        full_body: "Teljes test",
        chest: "Mell",
        back: "Hát",
        legs: "Láb",
        shoulders: "Váll",
        arms: "Kar",
        core: "Törzs",
        cardio: "Kardió",
        mobility: "Mobilitás",
        none: "Nincs",
        bodyweight: "Saját súly",
        dumbbells: "Kézisúlyzó",
        barbell: "Rúd",
        kettlebell: "Kettlebell",
        machine: "Gép",
        bands: "Szalagok",
        other: "Egyéb",
        training_schedule: "Edzésterv",
        manage_sessions_bookings: "Kezelje edzéseit és foglalásait",
        create_new_session: "Új edzés létrehozása",
        upcoming_sessions: "Közelgő edzések",
        pick_date_time: "Válasszon dátumot és időt",
        capacity: "Kapacitás",
        duration_min: "Időtartam (perc)",
        individual_tip: "Az egyéni edzések automatikusan 1-es kapacitásúak.",
        no_sessions_scheduled: "Nincsenek ütemezett edzések",
        awaiting_booking: "Foglalásra vár",
        no_program_yet: "Még nincs program",
        confirm_cancel_term: "Biztosan lemondja ezt az edzést?",
        term_created: "Edzés létrehozva! Az ügyfelek most foglalhatnak.",
        term_canceled: "Edzés lemondva",
        browse_book_sessions: "Edzések böngészése és foglalása",
        filter_search: "Szűrés és keresés",
        all_types: "Minden típus",
        all_sessions: "Minden edzés",
        free: "Szabad",
        full: "Betelt",
        enrolled: "Beírva",
        book: "Foglalás",
        booking: "Foglalás",
        canceling: "Lemondás",
        not_cancellable: "Nem mondható le",
        no_sessions_found_msg: "Nem találhatók edzések",
        try_adjusting_filters: "Próbálja módosítani a szűrőket",
        search_sessions: "Edzések keresése...",
        session_booked: "Edzés lefoglalva",
        booking_failed: "Foglalás sikertelen",
        my_programs: "Programjaim",
        programs_of_trainer: "Az edző programjai",
        no_trainer_assigned: "Nincs edző hozzárendelve",
        select_trainer_msg: "Válasszon edzőt a programjaik megtekintéséhez.",
        all_levels: "Minden szint",
        apply: "Alkalmaz",
        view_details: "Részletek",
        author: "Szerző",
        loading_programs: "Programok betöltése",
        no_programs_found_msg: "Nem találhatók programok a megadott szűrőkkel.",
        no_programs_for_you: "Az edzőnek jelenleg nincsenek programjai az Ön számára.",
        try_adjusting_search: "Próbáljon más keresést vagy szintet.",
        loading_profile: "Profil betöltése",
        choose_trainer: "Edző választása",
        pick_trainer_subtitle: "Válasszon edzőt az edzések és programok feloldásához",
        no_trainers_available: "Nincsenek elérhető edzők",
        selecting: "Kiválasztás",
        create_session: "Edzés létrehozása",
        notes: "Megjegyzések",
        position: "Pozíció",
        delete_program: "Program törlése",
        delete_program_confirm: "Biztosan törölni szeretné ezt a programot?",
        program_deleted: "Program törölve",
        program_saved: "Program mentve",
        move_up: "Felfelé",
        move_down: "Lefelé",
        remove: "Eltávolítás",

        // Billing / Plans
        change_plan: "Csomag váltása",
        plan: "Csomag",
        pending: "Folyamatban",
        pending_requests: "Ügyfélkérelmek",
        pending_msg: "Ütemezett váltás erre a csomagra:",
        price: "Ár",
        next_renewal: "Következő megújítás",
        no_plan_found: "Nincs aktív előfizetés.",
        client_count: "Ügyfelek",
        billing_status: "Számlázási állapot",
        trial_end: "Próba vége",
        month: "hónap",
        activate: "Aktivál",
        current: "Aktív",
        downgrade: "Lefokozás",
        upgrade: "Frissítés",
        activate_plan_note: "Havonta megújul az aktiválás napján.",
        using_clients: "{current} / {max} ügyfélhely használatban",
        unlimited: "Korlátlan",
        your_plan: "Saját csomagod",
        active_plan: "Aktív csomag",
        pending_plan_change: "Függőben lévő csomagváltás",
        no_pending_requests: "Nincs függőben lévő kérelem.",
        approve: "Jóváhagyás",
        client_signup_note: "Ez a regisztráció csak ügyfeleknek. Edzői fiókok a kapcsolat űrlapon, admin jóváhagyással jönnek létre.",
        create_client: "Ügyfél létrehozása",
        create_client_account: "Ügyfélfiók létrehozása",
        password: "Jelszó",
        birth_date: "Születési idő",
        enter_name: "Adja meg a nevet",
        enter_surname: "Adja meg a vezetéknevet",
        creating_account: "Fiók létrehozása...",
        success_create_client: "Ügyfélfiók sikeresen létrehozva",
        failed_create_client: "Nem sikerült létrehozni a fiókot",
        error_create_client: "Hiba a fiók létrehozásakor",
        fill_details_below: "Töltse ki az alábbi adatokat",
        billing_and_plans: "SZÁMLÁZÁS ÉS CSOMAGOK",
        subscription_overview: "Előfizetés áttekintése",
        available_plans: "Elérhető csomagok",
        account_not_active: "A fiók nem aktív",
        select_plan_to_continue: "Válasszon egy csomagot a TrainMeter használatának folytatásához.",
        overview: "Áttekintés",
        client_requests_title: "ÜGYFÉLKÉRELMEK",
        no_new_requests: "Nincs új kérelem",
        client_request_empty_desc: "Amikor egy ügyfél kérelmet küld, itt fogja látni.",
        trial: "Próbaverzió",
        active: "Aktív",
        past_due: "Lejárt",
        suspended: "Felfüggesztve",
        inactive: "Inaktiv",
        current_plan: "Jelenlegi csomag",
        select_plan: "Csomag kiválasztása",
        upgrade_scheduled: "Frissítés (ütemezve)",
        downgrade_scheduled: "Visszafejlesztés (ütemezve)",
        plan_already_scheduled: "A csomag már ütemezve van",
        trial_ends_in_plural: "A próbaidőszak {days} nap múlva lejár!",
        trial_ends_in_singular: "A próbaidőszak {days} nap múlva lejár!",
        trial_period_days: "Próbaidőszak — még {days} nap van hátra",
        select_plan_to_avoid_break: "Válasszon csomagot most a szolgáltatások megszakításának elkerülése érdekében.",
        try_all_features_free: "Próbálja ki az összes funkciót ingyen. Válasszon csomagot, ha készen áll.",
        appointment_created_assigned: "Időpont létrehozva és hozzárendelve: {name}",
        appointment_slot_created: "Időpont létrehozva! Az ügyfelek most már lefoglalhatják.",
        up_to: "akár",
        error_loading_billing: "Hiba a számlázási adatok betöltésekor",
        manage_subscription_limits: "Előfizetések és limitek kezelése",
        downgrade_scheduled_msg: "A {plan} csomagra való visszafejlesztés a következő számlázási ciklusra van ütemezve.",
        not_provided: "Nincs megadva",
        error_canceling_session: "Hiba az időpont lemondásakor",
        cancellation_failed: "A lemondás nem sikerült",
        term_deleted: "Időpont törölve",
        list: "Lista",
        all_groups: "Összes csoport",
        add_to_program: "Hozzáadás a programhoz",
        new_program: "Új program",
        edit_program: "Program szerkesztése",
    }
};

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [theme, setThemeState] = useState<Theme>((localStorage.getItem('trainmeter-theme') as Theme) || 'dark');
    const [language, setLanguageState] = useState<Language>((localStorage.getItem('trainmeter-lang') as Language) || 'English');

    useEffect(() => {
        document.documentElement.className = theme;
        localStorage.setItem('trainmeter-theme', theme);
    }, [theme]);

    useEffect(() => {
        localStorage.setItem('trainmeter-lang', language);
    }, [language]);

    const setTheme = (t: Theme) => setThemeState(t);
    const setLanguage = (l: Language) => setLanguageState(l);

    const t = (key: string) => {
        return translations[language][key] || translations['English'][key] || key;
    };

    return (
        <SettingsContext.Provider value={{ theme, language, setTheme, setLanguage, t }}>
            {children}
        </SettingsContext.Provider>
    );
};

export const useSettings = () => {
    const context = useContext(SettingsContext);
    if (!context) throw new Error('useSettings must be used within SettingsProvider');
    return context;
};
